version: "2"
checks:
  method-complexity:
    config:
      threshold: 6
  method-lines:
    config:
      threshold: 50
exclude_paths:
  - "node_modules/"
  - "public/"
  - ".cache/"
  - ".emotion-cache/"
  - "src/gatsby-types.d.ts"

